---
# tasks file for vpc_deployment
    - name: Create VPC
      ec2_vpc_net:
        state: present
        name: "{{ vpc_name }}"
        cidr_block: "{{ cidr_net }}"
        region: "{{ region }}"
      register: vpc_net
    - name: Create Subnet
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{ vpc_net.vpc.id }}"
        cidr: "{{ cidr_subnet }}"
        region: "{{ region }}"
        map_public: true
      register: vpc_subnet
    - name: Create Security Group
      ec2_group:
        state: present
        name: "{{ sg_name }}"
        description: "{{ sg_description }}"
        region: "{{ region }}"
        vpc_id: "{{ vpc_net.vpc.id }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
      register: sg_vpc
