---
- hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - role: vpc_deployment
      vpc_name: myvpc
      cidr_net: 10.0.0.0/16
      cidr_subnet: 10.0.1.0/24
      region: us-west-1
      sg_name_linux: aneesh_ssh_sg
      sg_description_linux: Aneesh SG for ssh
      when: os_type == "Linux"
    - role: ec2_deployment
      count: 1 
      server_name: TomcatServer
      instance_type: t2.micro
      region: us-west-1
      assign_public_ip: yes
      ami: ami-18726478
      key_name: my_key
      key_location: ./my_key.pem
      when: os_type == "Linux"
- hosts: patch_inventory
  become: yes
  roles:
    - role: patch_deployment
