---
- hosts: localhost
  connection: local
  gather_facts: no
  vars: 
    instance_type: t2.micro
    ami: ami-18726478 
    region: us-west-1
    pem: aneesh-kp
    secgroup: aneesh-ssh-sg
    count: 1
    subnet: subnet-d8110fbf
    assign_public_ip: yes
    os_name: RHEL7.5

  tasks:
  - name: Launch "{{ os_name }}" EC2 instances
    ec2:
      region: "{{ region }}"
      key_name: "{{ pem }}"
      group: "{{ secgroup }}"
      instance_type: "{{ instance_type }}"
      image: "{{ ami }}"
      wait: yes
      count: "{{ count }}"
      vpc_subnet_id: "{{ subnet }}"
      assign_public_ip: "{{ assign_public_ip }}"
  - name: Gathering EC2 details
    ec2_instance_facts:
      filters:
        instance-state-name: running
        instance-type: "{{ instance_type }}"
        image-id: "{{ ami }}"
      region: "{{ region }}"
    register: ec2
  - name: Waiting for SSH to come up
    wait_for:
      host: "{{ item.public_dns_name }}"
      port: 22
      delay: 60
      timeout: 120
      state: started
    with_items: "{{ ec2.instances }}"
    no_log: True
    register: ssh_result
    ignore_errors: yes
  - fail:
      msg: "Something went wrong, not able to establish ssh connection to the newly created VM. Please check VM status from AWS console and it's SG/ACL policies"
    when: ssh_result is failed
  - debug:
      msg: "Successfully launched '{{ count }}' instance with name '{{item.public_dns_name }}' and with IP '{{item.public_ip_address}}' and SSH connection established"
    with_items: "{{ ec2.instances }}"
