---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    vpc_name: myvpc
    cidr_net: 10.0.0.0/16
    cidr_subnet: 10.0.1.0/24
    region: us-west-1
  tasks:
    - name: Create VPC
      ec2_vpc_net:
        state: present
        name: "{{ vpc_name }}"
        cidr_block: "{{ cidr_net }}"
        region: "{{ region }}"
      register: vpc_net
    - name: Create Subnet
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{ vpc_net.vpc.id }}"
        cidr: "{{ cidr_subnet }}"
        region: "{{ region }}"
        map_public: true
      register: vpc_subnet
        
