---
# tasks file for ec2_deployment
  - name: Launch "{{ os_name }}" EC2 instances
    ec2:
      region: "{{ region }}"
      key_name: "{{ pem }}"
      group: "{{ secgroup }}"
      instance_type: "{{ instance_type }}"
      image: "{{ ami }}"
      wait: yes
      count: "{{ count }}"
      vpc_subnet_id: "{{ subnet }}"
      assign_public_ip: "{{ assign_public_ip }}"
    register: ec2
  - name: Waiting for SSH to come up
    wait_for:
      host: "{{ item.public_ip }}"
      port: 22
      delay: 60
      timeout: 120
      state: started
    with_items: "{{ ec2.instances }}"
    no_log: True
    register: ssh_result
    ignore_errors: yes
  - name: Checking the success of VM creation and SSH connection
    fail:
      msg: "Something went wrong, not able to establish ssh connection to the newly created VM. Please check VM status from AWS console and it's SG/ACL policies"
    when: ssh_result is failed
  - debug:
      msg: "Successfully launched '{{ count }}' instance with name '{{item.public_dns_name }}' and with IP '{{item.public_ip}}' and SSH connection established"
    with_items: "{{ ec2.instances }}"
