---
- name: Winows - download the 7-Zip package
  win_get_url:
    url: http://www.7-zip.org/a/7z1701-x64.msi
    dest: C:\7z.msi

- name:  Windows - Install the 7-Zip package
  win_package:
    path: C:\7z.msi
    state: present
