---
# tasks file for ec2_deployment
  - name: Gathering existing EC2 instance details
    ec2_instance_facts:
      region: "{{ region }}"
      filters:
        tag:Name: "{{ server_name }}"
        instance-state-name: running
    register: existing_ec2
  - name: Launch "{{ os_type }}" EC2 instances
    ec2:
      region: "{{ region }}"
      key_name: "{{ key_name }}"
      group: "{{ secgroup }}"
      instance_type: "{{ instance_type }}"
      image: "{{ ami }}"
      wait: yes
      count: "{{ count }}"
      vpc_subnet_id: "{{ subnet }}"
      assign_public_ip: "{{ assign_public_ip }}"
      instance_tags:
        Name: "{{ server_name }}"
    register: ec2
    when: existing_ec2.instances == [] 
  - debug:
      msg: "{{ ec2 }}"
  - name: Checking if an Instance exists with same name; fail if there is instance with same name or skip this task and proceed to create the Instance 
    fail:
      msg: "The Instance with name'{{ server_name }}' already exists. Please crete the Instance with another name"
    when: existing_ec2.instances != []
  - name: Waiting for SSH to come up for a Linux Server
    wait_for:
      host: "{{ item.public_ip }}"
      port: 22
      delay: 60
      timeout: 120
      state: started
    with_items: "{{ ec2.instances }}"
    no_log: True
    register: ssh_result
    ignore_errors: yes
    when: os_type == "Linux"
  - name: Checking the success of VM creation and SSH connection. Skip if success or fail otherwise
    fail:
      msg: "Something went wrong, not able to establish ssh connection to the newly created VM. Please check VM status from AWS console and it's SG/ACL policies"
    when: 
      - ssh_result is failed
      - os_type == "Linux"
  - debug:
      msg: "Successfully launched '{{ count }}' instance with name '{{item.public_dns_name }}' and with IP '{{item.public_ip}}'"
    with_items: "{{ ec2.instances }}"
  - name: Add the newly added Linux Instances to a Dynamic Inventory
    add_host:
      name: "{{ item.public_ip }}"
      groups: patch_inventory
      ansible_ssh_user: ec2-user
      ansible_ssh_private_key_file: "{{ key_location }}" 
    with_items: "{{ ec2.instances }}"  
    no_log: True
    when: os_type == "Linux"
#  - name: Add the newly added Windows Instances to a Dynamic Inventory
#    add_host:
#      name: "{{ item.public_ip }}"
#      ansible_user: "{{ windows_admin_user }}"
#      ansible_password: "{{ windows_admin_passwd }}"
#      ansible_connection: winrm
#      ansible_port: 5986
#      ansible_winrm_server_cert_validation: ignore
#      ansible_winrm_transport: ssl
#      groups: windows_vms
#    with_items: "{{ ec2.instances }}"
#    when: os_type == "Windows"
